export const QUERY = "?api_key="
export const API_KEY = "aa0526c566a1bb6b23e2e2d2eea4c4ce";
export const URL = "https://api.themoviedb.org/3/";
export const GET_MOVIE = "GET_MOVIE";
export const GET_MOVIE_BY_ID = "GET_MOVIE_BY_ID";
export const GET_MOVIE_BY_NAME = "GET_MOVIE_BY_NAME"
export const FILTER_BY_AVERAGE0_2 = "FILTER_BY_AVERAGE0_2";
export const FILTER_BY_AVERAGE2_4 = "FILTER_BY_AVERAGE2_4";
export const FILTER_BY_AVERAGE4_6 = "FILTER_BY_AVERAGE4_6";
export const FILTER_BY_AVERAGE6_8 = "FILTER_BY_AVERAGE6_8";
export const FILTER_BY_AVERAGE8_10 = "FILTER_BY_AVERAGE8_10";